// Code generated by go generate; DO NOT EDIT.
package conf

func GetProviderList() []Provider {
	return []Provider{
		{
			Repo: "sing-box", 
			Owner: "SagerNet", 
			Version: []string{
				"v1.9.0-alpha.15",
				"v1.8.8",
			},
		},
		{
			Repo: "mihomo", 
			Owner: "MetaCubeX", 
			Version: []string{
				"v1.18.1",
			},
		},
	}
}
