// Code generated by go generate; DO NOT EDIT.
package provider

import "github.com/hvturingga/ya/conf"

func GetProviderList() []conf.Provider {
	return []conf.Provider{
		{Repo: "sing-box", Owner: "SagerNet", Version: "v1.9.0-alpha.15"},
		{Repo: "mihomo", Owner: "MetaCubeX", Version: "v1.18.1"},
	}
}
