// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Daemon is the predicate function for daemon builders.
type Daemon func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// Subscribe is the predicate function for subscribe builders.
type Subscribe func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
